version: '3.8'

services:
  app:
    container_name: nest-http
    image: nest/nest-http:latest
    command: node index.js --redis_host=redis --db_host=mongo --allowed_origins=${ALLOWED_ORIGINS} --jwt_secret=${JWT_SECRET} --color --cluster
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
    restart: 'on-failure'
    volumes:
      - ./data/nest:/root/.nest

    ports:
      - '3333:3333'
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '3344:27017'
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis

    ports:
      - '6560:6379'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
